orbs:
  architect: giantswarm/architect@0.10.1

version: 2.1
workflows:
  build:
    jobs:
      # build operator
      - architect/go-build:
          name: go-build
          binary: azure-operator
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      # build and push docker image to quay
      - architect/push-to-docker:
          name: push-azure-collector-to-quay
          image: "quay.io/giantswarm/azure-collector"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      # build and push helm chart to app catalog
      - architect/push-to-app-catalog:
          name: push-azure-collector-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "azure-collector"
          # Make sure docker image is successfully built.
          requires:
            - push-azure-collector-to-quay
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      # deploy to installations
      - architect/push-to-app-collection:
          name: push-azure-collector-to-azure-app-collection
          app_name: "azure-collector"
          app_collection_repo: "azure-app-collection"
          unique: "true"
          requires:
            - push-azure-collector-to-control-plane-app-catalog
          filters:
            # Do not trigger the job on commit.
            branches:
              ignore: /.*/
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
