apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "azure-collector.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      azure:
        controlplaneresourcegroup: '{{ .Values.Installation.V1.Name }}'
        environmentName: '{{ .Values.Installation.V1.Provider.Azure.Cloud }}'
        location: '{{ .Values.Installation.V1.Provider.Azure.Location }}'
      kubernetes:
        incluster: true
