apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "azure-collector.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      controlplaneresourcegroup: '{{ .Values.managementCluster.name }}'
      location: '{{ .Values.provider.location }}'
      kubernetes:
        incluster: true
