apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: {{ tpl .Values.resource.default.name  . }}-exceptions
  namespace: {{ tpl .Values.resource.default.namespace  . }}
spec:
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - Pod
        namespaces:
        - {{ tpl .Values.resource.default.namespace  . }}
        names:
        - {{ tpl .Values.resource.default.name  . }}*
