apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "azure-collector.labels" . | nindent 4 }}
stringData:
  secret.yaml: |
    service:
      azure:
        clientID: {{ .Values.provider.credentials.clientID | quote }}
        clientSecret: {{ .Values.provider.credentials.clientSecret | quote }}
        sptenantID: {{ .Values.provider.credentials.sptenantID | quote }}
        subscriptionID: {{ .Values.provider.credentials.subscriptionID | quote }}
        tenantID: {{ .Values.provider.credentials.tenantID | quote }}
