apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "azure-collector.labels" . | nindent 4 }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
    giantswarm.io/monitoring: "true"
  annotations:
    prometheus.io/scrape: "true"
{{- end }}
spec:
  type: NodePort
  ports:
  - name: web
    port: 8000
  selector:
    {{- include "azure-collector.selectorLabels" . | nindent 4 }}
