apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "azure-collector.labels" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    {{- include "azure-collector.selectorLabels" . | nindent 4 }}
